### ISSUE TITLE
Cache: Workers Close with NoMethodError: undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by rye** [rye/old-krye.io#47]
Ripperino, I should have thought of this.  Here is some example output.

```
F, [2016-08-13T11:56:23.609276 #2432] FATAL -- Worker [0] EXITING: NoMethodError: undefined method `map' for nil:NilClass
Did you mean?  tap
        /Users/kristofer/Documents/Development/GitHub/rye/krye.io/lib/site/cache.rb:222:in `block (4 levels) in spawn_workers'
        /Users/kristofer/Documents/Development/GitHub/rye/krye.io/lib/site/cache.rb:196:in `synchronize'
        /Users/kristofer/Documents/Development/GitHub/rye/krye.io/lib/site/cache.rb:196:in `block (3 levels) in spawn_workers'
        /Users/kristofer/Documents/Development/GitHub/rye/krye.io/lib/site/cache.rb:129:in `loop'
        /Users/kristofer/Documents/Development/GitHub/rye/krye.io/lib/site/cache.rb:129:in `block (2 levels) in spawn_workers'
```

**Comment by rye** [comment]
It appears that this error shows up because the result from [the case statement](https://github.com/rye/krye.io/blob/e84722f646bdebce928dd5a216583c89dfe778be/lib/site/cache.rb#L201-L220) is nil, and we're not checking for that case. (which is the `else`)

**Comment by rye** [comment]
It appears that the primary solution here will be to do type-checking and toss out a `Site::Logger.warn` if the system is unable to generate the list of routes that it wants.  We don't generate routes for these swap files, but they do show up in the Listener feed, especially during active development, so we should toss them if they don't work.
